### ISSUE TITLE
RC2014 w/ TMS9918A: weird behavior with multiple TTYs

### ISSUE THREAD

**Issue by ry755** [EtchedPixels/FUZIX#1018]
Switching to a different TTY via the alt-Fx keys works, but upon pressing any key within that different TTY the computer hangs and the displayed cursor starts blinking quickly as if characters were being sent very quickly, but nothing appears on screen.

Also, spawning a shell on an alternate TTY (via editing /etc/inittab) partially works, it shows the login prompt but again, same issue with attempting to enter characters. This also applies to spawning a shell on the serial port (/dev/tty5), no characters can be entered.

This can be reproduced in the emulator with the following command: `./rc2014_sdl2 -s -r RCZ80_std.rom -b -i emu-ide.img -P -T`

**Comment by EtchedPixels** [comment]
Interesting - I've seen this on the emulation before it but it disappeared when I tried to debug it. I will have another look into it when I get time

**Comment by EtchedPixels** [comment]
Fixed. Silly bug with queue setup
