### ISSUE TITLE
No 0.4 tag in Github repository

### ISSUE THREAD

**Issue by brejoc** [EtchedPixels/FUZIX#1022]
Hi folks, I noticed that the Fuzix website mentions an 0.4 tag right at the top: "The matching tag is '0.4'."

I can't see any tag here. Am I looking at the [wrong spot](https://github.com/EtchedPixels/FUZIX/tags) or should there be tags?

**Comment by EtchedPixels** [comment]
Oh the joys of git push and git push --tags

Try now

**Comment by brejoc** [comment]
Awesome! That looks much better. Thanks a lot! 👍
