### ISSUE TITLE
sleep() and usleep() don't work at all, at least on my raspberry pi pico

### ISSUE THREAD

**Issue by duckyondiscord** [EtchedPixels/FUZIX#1039]
It's possible I did something wrong here, if so, I'm sorry for wasting your time.

In my testing, neither usleep() nor sleep() work, both of them just sleep forever no matter the argument.

**Comment by duckyondiscord** [comment]
I'll add the code I used to test it here:
```#include <stdio.h>
#include <unistd.h>

int main()
{
	printf("o/\n");
	usleep(5);
	printf("What's up?\n");
}```

**Comment by duckyondiscord** [comment]
Nothing too complicated

**Comment by duckyondiscord** [comment]
I'll close this as it magically started working after a few recompiles, weird..

**Comment by EtchedPixels** [comment]
If it comes back do open a bug. That's a bit weird
