### ISSUE TITLE
z80 build script recurses

### ISSUE THREAD

**Issue by mjgarton** [EtchedPixels/FUZIX#1043]
The first few lines of `Tools/build-z80` look like this.
```
#!/bin/sh
(./build-z80)
#
```

This seems to simply call itself. I am unsure what the intended behaviour is.

See https://github.com/EtchedPixels/FUZIX/blob/master/Tools/build-z80#L2

**Comment by EtchedPixels** [comment]
Thanks. Should be fixed now (still doesn't check for the right sdcc fork but does run the right z80u script)
