### ISSUE TITLE
Shell is unsuitable for scripting

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#105]
Current shell `/bin/ssh` is only usable for interactive usage, no script flow control implemented, such as:
* `if` / `then` / `else` / `fi`
* `case` / `esac`
* `for` / `do` / `done`
This makes us unable to use the toolbox approach on FUZIX we are used to on UNIX and the likes.
Related: #70 #76

**Comment by EtchedPixels** [comment]
The source for the original Bourne shell is now freed, but it need someone to port it from early K&R style C to ANSI C.

**Comment by erkinalp** [comment]
It is not even K&R C. It is worse, Pascal-ish C.

**Comment by erkinalp** [comment]
http://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/src/cmd/sh/cmd.c

**Comment by EtchedPixels** [comment]
Yes its written in mock Algol 8)

**Comment by erkinalp** [comment]
I am porting sash now. It has a bunch of builtins, such as gzip and tar. When finished stripping(yes, there are too many builtins), I am going to upload it.

**Comment by Zardoz89** [comment]
Thompson shell on ANSI C : https://github.com/JNeitzel/v6shell/blob/master/sh6.c

**Comment by erkinalp** [comment]
Its license is GPL-incompatible.

**Comment by EtchedPixels** [comment]
4 clause BSD. I don't really have a problem with that for add on tools

**Comment by erkinalp** [comment]
There is osh from v6 shell package, with the same licence. osh is 8-bit clean, where as v6shell is not. I have PRd in #106.

**Comment by erkinalp** [comment]
Trying to port toybox shell and utilities now. There are too many Linux specific bits in it.

**Comment by erkinalp** [comment]
@EtchedPixels: Are you satisfied with v7 Bourne shell scripting possibilities?

**Comment by EtchedPixels** [comment]
Yeah I think so - just needs ansifying

**Comment by EtchedPixels** [comment]
Bourne shell ported. Ok it's still slightly buggy and needs some tweaking but I think this one is closed
