### ISSUE TITLE
Z80-MBC2 emulation, bdwrite: panic: invalid dev, kernel trying to read from drive 0 while disk image name suggests drive 1

### ISSUE THREAD

**Issue by bastetfurry** [EtchedPixels/FUZIX#1095]
I am writing an emulator of the Z80-MBC2 platform, try to run Fuzix on it and run into some odd behavior that makes Fuzix panic on boot.

The headscratcher is that, according to the disk image name provided, the system should try to boot from disk device 1 but when i insert that image into my emulators drive 1 the Fuzix kernel isn't finding any disks and panics out.

```
[...]
128kB total RAM, 64kB available to processes (15 processes max)
Enabling interrupts ... ok.
hda: bdwrite:
panic: invalid dev
```

If i place the root image file into disk 0 he finds its partitions but still panics:
```
[...]
128kB total RAM, 64kB available to processes (15 processes max)
Enabling interrupts ... ok.
hda: hda1 (swap) hda2 bdwrite:
panic: invalid dev
```

Tracing the IO accesses i see that the kernel never tries to access drive 1 but only drive 0, but as the original filename is DS0N01.DSK, which has to be renamed to DS5N01.DSK on the original hardware, the kernel should expect it to be in drive 1 or am i missing something here?

My drive emulation should work fine by the way, both CP/M 2.2  and CP/M 3 run without any problems.

Both files, the bootfile and the disk, appear to be correct, checked the SHA256s against freshly downloaded ones.

I haven't implemented the RTC or the IO port yet, but from what i understand that shouldn't stop the kernel from booting.

**Comment by EtchedPixels** [comment]
The kernel does memory bank switching early on so if you don't have that working then it would bomb something like you describe.

**Comment by bastetfurry** [comment]
Yep, the MMU code had a little oopsie. Then i am puzzled why CPM3 ran just fine.
Sorry to have bothered you. -.-

**Comment by bastetfurry** [comment]
If someone else stumbles upon this, this is a working Z80 MBC2 MMU:
```
fast_u8 Z80Machine::on_read(fast_u16 addr)
{
    uint32_t realAddress = 0;
    if (addr < 0x8000)
    {
        switch (mmuState)
        {
            case 0:
                realAddress = addr | 0x8000;
                break;
            case 1:
                realAddress = addr | 0x18000;
                break;
            case 2:
                realAddress = addr | 0x10000;
                break;
        }
    }
    else
    {
        realAddress = addr & 0x7fff;
    }
    return memory[realAddress];
}
```

**Comment by EtchedPixels** [comment]
Cool - glad you found it.
