### ISSUE TITLE
Please tell me how to convert filesystem.ftl to suitable format for pico2

### ISSUE THREAD

**Issue by kazueda** [EtchedPixels/FUZIX#1123]
Dear Sir,
I am trying to boot FUZIX on a RP2350 board, such as a Raspberry Pi Pico2.
I made my filesystem.uf2 from built filesystem.ftl in accordance with the following command.
$ make image SUBTARGET=pico2 -j
$ arm-none-eabi-objcopy -I binary -O elf32-littlearm --change-section-vma .data=0x10018000 filesystem.ftl filesystem.elf
$ ./uf2conv filesystem.ftl filesystem.uf2 0x10018000
A uf2conv command was imported from the v.0.4 archive.

I put my built fuzix.uf2 and filesystem.uf2 on my pico2 board.
My fuzix.uf2 works fine but I cannot select any drive on the "bootdev:" prompt.
![image](https://github.com/user-attachments/assets/cfac9b36-aa27-46b4-94b6-fa5cd9a2a178)

Sincerely yours,
kazueda

PS My fuzix.uf2 and filesystem.uf2 for Raspberry Pi Pico obtained similar procedure above works fine and I can login to the Fuzix system.  In this case I type "0", which means sero, to the "bootdev:" prompt.
![image](https://github.com/user-attachments/assets/c7460540-2002-4491-8d3b-b7b61278c20d)

**Comment by kazueda** [comment]
Thank you for your reply. Pico2 will not use filesystem.uf2 on PSRAM.

**Comment by neonquill** [comment]
I just wiped my board and verified that a normal filesystem `cp` does **not** work for me (specifically `cp filesystem.uf2 /Volumes/RP2350/`). I get the same mount failure.
I then tried using `picotool load filesystem.uf2` which then works fine (selecting `hda` at the bootdev prompt leads to the mount succeeding).

**Comment by kazueda** [comment]
Thank you for your advice.
I can boot FUZIX in use of a rootfs on my PICO2 board.
PS
In order to load a filesystem.uf2 on the PICO2 board, picotool on raspberry pi repository is needed.

**Comment by veremenko-y** [comment]
@kazueda 
Once #1139 is merged, uploading filesystem.uf2 onto pico2 should work again.

**Comment by kazueda** [comment]
Thank you for your comment.
I will try later.
