### ISSUE TITLE
Modifications to Accurately Write the Time to an RTC

### ISSUE THREAD

**Issue by dennowiggle** [EtchedPixels/FUZIX#1124]
The `setdate` application is used to write the current time to the RTC with the `-w` option. 

In the `rtcwrite()` function in `Applications/util/setdate.c` there is a `puts("writing\n");` statement between reading the current system time and calling the platform RTC write function `plt_rtc_write()`. The statement should be deleted or moved so that writing to the console does not make the stored time stale before writing to the RTC.

When writing the time to the platform RTC, the `rtcsec` variable in `Kernel/timer.c` needs to be resynced to the new RTC seconds time by calling `inittod()`. One option to do this is to call function `inittod()` from the `plt_rtc_write() function`. One driver where this could be done is `Kernel/dev/ds12885.c`. I'm not sure if any other platform drivers currently write to an RTC to set the time.
```
#ifdef CONFIG_RTC_INTERVAL
		inittod();
#endif
```

In function `inittod()` in `Kernel/timer.c` the following statement should be added to make sure the system time seconds is properly synced to the RTC seconds time. This is important when writing a new time to the RTC so the seconds are synced accurately.
`	tod_deci = 0;`
Function becomes
```
void inittod(void)
{
	rtcsec = plt_rtc_secs();
	tod_deci = 0;
}
```

I tested this solution on my custom eZ80 platform.

**Comment by EtchedPixels** [comment]
Thanks - added
