### ISSUE TITLE
Safe shutdown

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#121]
FUZIX currently lacks an utility to shutdown or reboot the system safely. I understand, we have no APM on most of the targets, yet anyway could we implement a utility that does:
* SIGTERM, wait for save and SIGKILL
* Disable network
* Unmount non-root FSs
* Remount rootfs readonly
* Prompt for poweroff

**Comment by EtchedPixels** [comment]
The uadmin syscall already supports reboot/poweroff to the limit of hardware support, so a simple reboot app is trivial enough. Doing anything complex needs to wait until we have a fuller userspace, if it ever makes sense.

**Comment by EtchedPixels** [comment]
Minimal reboot command added
