### ISSUE TITLE
Cowsay

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#155]
The game which displays speech bubbles, companion of fortune. A version written in C preferred.

**Comment by EtchedPixels** [comment]
____________________________________ 
/ That would be silly, and anyway it \
\ needs perl                         /
 ------------------------------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by erkinalp** [comment]
https://github.com/0xAether/ccowsay
This is in C.

**Comment by erkinalp** [comment]
Ccowsay is in GPLv3, unsuitable for inclusion.

**Comment by erkinalp** [comment]
https://github.com/shkschneider/c_unix/blob/master/cowsay.c
This is in GPLv2 as specified in its readme.

**Comment by erkinalp** [comment]
PR made in #156.

**Comment by erkinalp** [comment]
/ This is         \
    \ written in C. /
    
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by erkinalp** [comment]
Now in #157.
