### ISSUE TITLE
Use LLC for Z80 targets

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#159]
SDCC is single-pass and cannot perform optimisations. Z80 targets may have smaller and faster binaries if we switch to LLVM toolchain for Z80. 
See: https://github.com/earl1k/llvm-z80

**Comment by EtchedPixels** [comment]
SDCC performs extensive optimization, not sure where you got the idea it didn't. It also has active maintainers.

llvm-z80 appears to have died anyway
