### ISSUE TITLE
build-filesystem

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#169]
Need a script to build a minimalist file system. Some of our machines only have 40 track floppies.

**Comment by EtchedPixels** [comment]
Now have a script for building a smaller file system but probably want to go smaller still

**Comment by EtchedPixels** [comment]
Down to 140K.. probably about the limit we can push

**Comment by erkinalp** [comment]
Still too much. I expected it to fit  in a 20-track/side, 2-side, 8
sector/track, 256b/sector ie. 80k floppy diskette.
23 May 2015 02:39 tarihinde "EtchedPixels" <notifications@github.com> yazdı:
>
> probably about the limit we can push
>
> —
>

**Comment by EtchedPixels** [comment]
Not a chance, not with any material number of commands. We can fit a small fs in 140K, that should be fine.  A 3"  SD disk is 180K, a 5.25" 80 track SS disk is 200K, an Apple II disk is 140K.

**Comment by erkinalp** [comment]
Seems possible with my single-user PR applied along with DOS-like set of utilities(init,sh,mkdir,rmdir,mknod,chmod,chown,cp,mv,rm,ed)

**Comment by EtchedPixels** [comment]
Having the user features in the kernel costs nothing - no patch is needed. You can just not bother supporting it in your userspace and run always as root.

Yes you could probably build a sort of micro-shell with minimal versions of the core commands in, even then I suspect it would be very tight to get all that into the space and fitting into memory as one or two binaries with links in the busybox style.
