### ISSUE TITLE
tormodvolden contributing via unusual way

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#191]
Tormod Volden does not use usual way of contributing on GitHub despite having a GitHub account, instead, he sends e-mail patches to Alan as far as I see. Is he a contract worker for FUZIX?

**Comment by EtchedPixels** [comment]
No he just prefers to send patches via email. Tormod does the 6809 port and also designs hardware toys for the Dragon 32 boxes

**Comment by tormodvolden** [comment]
I am contracted by Dragon Data Ltd. They were a bit slow on that OS-9 thing, but they are not gonna miss the FUZIX train. Alan has promised a framebuffer with **lowercase** letters (!) so this time the educational market won't fail.

"git send-email" *is* the way to contribute to open-source projects. Real men and wise women don't rely on a proprietary web service to get their sh#t done. And I find all the "merge" commits in the log for single commits annoying.

**Comment by erkinalp** [comment]
GitHub has its own command line tool called hub for this purpose. All repository operations(including creating pull requests and commenting) can be done using this tool and it uses proffessional GitHub API, not the web one.

**Comment by erkinalp** [comment]
@tormodvolden: If you rebase commit to the upstream and merge using git's command line tool, you should not see that behavior.

**Comment by EtchedPixels** [comment]
git send-email works perfectly well.

**Comment by erkinalp** [comment]
> I am contracted by Dragon Data Ltd.

It was bankrupted long ago according to Wikipedia.

**Comment by EtchedPixels** [comment]
#include <humour.h>

**Comment by erkinalp** [comment]
Error: illegitimate include file "/usr/include/humour.h" which is not a regular file but is a device node
