### ISSUE TITLE
Swap optimisation

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#192]
We need to move u_top into p->p_top. That also means we can make the swapper write out only the area required on a chmem app. However we then need some logic to always write out the udata/

**Comment by davidgiven** [comment]
Assuming that the stack exists from p_sp to p_top isn't necessarily valid: it's legal for a process to change stack pointer, e.g. if it's doing threads or coroutines. If this happens, p_sp < u_break, and we've lost track of where the original stack actually begins. I suppose a workaround could be to save the entire user workspace in this situation.
