### ISSUE TITLE
Something is still fragile in the sh memory allocator

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#195]
Need to cross compare with the Heirloom codebase and look for any other fixes. While at it also import fixes for 32bit not just 16bit hosts.

**Comment by erkinalp** [comment]
Would fixes for 32 bit architectures not cause slowdown for 8 bit ones?

**Comment by EtchedPixels** [comment]
Shouldn't do

**Comment by EtchedPixels** [comment]
Added some fixes. 32bit will still break as we need to clean up the types further, but it now uses intptr_t for some stuff.

Now works on 6809. Memory handling hopefully cured in general. Needs more Z80 testing to close
