### ISSUE TITLE
POSIX 1:2008 and C11 library support

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#197]
FUZIX now has a limited C11 support(gets_s, as contributed by me) and no POSIX 1:2008 support. It seems feasible to support at least non-thread related parts of these two specs.

**Comment by EtchedPixels** [comment]
I think I'm more concerned about parity with iBCS2 and then perhaps worrying about SVID before worrying about completeness versus some of the other standards (although I'm all for stealing good bits from anywhere - hence strlcpy and friends, snprintf and gets_s are clear wins)

**Comment by erkinalp** [comment]
_s family planned to be removed from ISO C:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm
