### ISSUE TITLE
Change fork() to _fork(flags, ...) to allow for interesting hacks and future plaforms

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#198]
If we optimise the bank copiers to copy only base->brk and sp->top (plus fix the fact brk ought to zero the hole) then that speeds things up. It also means we could implement a rather quirky but very small fork-like API which moved the child stack pointer to the top of the low say 1K and copied only the bottom 1K. That would mean that with some tiny helpers packed low by using a special link section to force the references after crt0.s we'd be able to implement a very compact 'spawn' API set and some other things of that nature with almost no kernel code.

That would mean making for take a flags argument, which might be useful later for other platforms that can do true vfork etc.

**Comment by erkinalp** [comment]
> That would mean making for take a flags argument

Later it could turn into spawn()
