### ISSUE TITLE
More floating point routines

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#213]
Maths library needed in assembly to fill in `<math.h>`, `<float.h>` and `<complex.h>` family of functions.
EDIT: markdown parser ate part of comment.

**Comment by EtchedPixels** [comment]
All the relevant pieces should be coming from the compiler support library already and do so for gcc and for sdcc. cc65 doesn't support floating point.

So I don't see a bug here

**Comment by erkinalp** [comment]
http://www.6502.org/source/floats/wozfp1.txt

**Comment by EtchedPixels** [comment]
The compiler doesn't support float point types at all. A few fp routines in asm won't change that

**Comment by erkinalp** [comment]
Filed a feature request in cc65: https://github.com/cc65/cc65/issues/234
