### ISSUE TITLE
C11 stdio locked fopen() freopen() mode

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#219]
"x" mode should cause file to be opened locked exclusively. This also requires implementation of O_EXCL at Unix calls levels.

**Comment by EtchedPixels** [comment]
While you can support "x" the C11 changed behaviour for "w" or "a" directly contradicts SVID and Unix standard behaviour.

O_EXCL is supported as is 3 argument open so all of these can be done but I'm dubious it is a good idea. Possibly it needs a separate -lc11 library one day. Certainly not a short term priority.

**Comment by erkinalp** [comment]
> While you can support "x" the C11
> changed behaviour for "w" or "a"

Exclusive lock can be used for reading too(.i.e. "ex") Nobody else can read the file.  
This is default semantics with e.g. win32 and useful for network file servers.

**Comment by EtchedPixels** [comment]
Its not supported in Unix at all, and a nightmare on networks so while x makes sense mandatory exclusive access locks are just not going to happen

**Comment by erkinalp** [comment]
@EtchedPixels: There is no mandatory exclusive file lock on Windows either. Just comes by default, unlike Unix file open API, whilst shared locking is also available by calling relevant flag getting the file handle. What prevents an optional exclusive read lock aka "rx"?

**Comment by EtchedPixels** [comment]
Windows implements mandatory locking - if you open a file for exclusive access nobody else can access it. That causes nightmares on networked systems and multi-user environments so the model used by flock() is advisory locking. Processes can choose to co-operate but anyone else with access to the file can choose not to bother.

**Comment by erkinalp** [comment]
> Processes can choose to co-operate but
> anyone else with access to the file can
> choose not to bother.

What about file consistency in an exclusive locked file? Would partially modified files not cause issues on "I am the king, ignoring everyone else" side?

**Comment by EtchedPixels** [comment]
Yes.. but that's not a problem the Unix OS tries to solve. An OS can't solve it because transactions are usually not single file based.
