### ISSUE TITLE
Get rid of proprietary web service dependency

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#222]
Move the main repository to a server which is maintainable and accessible by the maintainer and packagers if they want, using free software infrastructure such as Alioth, Trac, GitLab community edition. http://fuzix.org stands still. A subdomain of it seems logical place for such a repository.
tormodvolden said:
> Real men and wise women don't rely on a proprietary web service

**Comment by EtchedPixels** [comment]
We don't rely on github, we just use it and it works fine.

**Comment by erkinalp** [comment]
@tormodvolden: Not solved. Still relying on proprietary software.

**Comment by erkinalp** [comment]
@EtchedPixels Microsoft has bought github.
