### ISSUE TITLE
variable swapcnt usage inconsistant across memory map types

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#240]
"bank16.c" and "bank16low.c" treat swapcnt as a count of disk blocks (aka 512 bytes).  "simple.c" and "fixed.c" treat swapcnt as a count of plain bytes.

**Comment by EtchedPixels** [comment]
Should be bytes. We'll be doing maths for these anyway once we start swapping just the bits that need to hit disk (at least for cases its faster)

**Comment by beretta42** [comment]
pull requested code to fix this.  Currently, no 16k platforms implement swap yet, so nothing *should* break.
