### ISSUE TITLE
Rename repository name to "fuzix"

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#244]
This will make life of fork makers intending to make use of a package manager.

**Comment by erkinalp** [comment]
easier.

**Comment by EtchedPixels** [comment]
If your package manager isn't smart enough to let you set a name then fix your package manager

**Comment by erkinalp** [comment]
.deb and .rpm packages always use lowercase names.

**Comment by EtchedPixels** [comment]
1. They don't
2. They don't care what the git repository name is when setting the package name

**Comment by erkinalp** [comment]
Done in local fork.

**Comment by erkinalp** [comment]
> If your package manager isn't smart enough to let you set a name then fix your package manager

Tell this to maven folks.
