### ISSUE TITLE
Conflicting types for getmode

### ISSUE THREAD

**Issue by gustauperez** [EtchedPixels/FUZIX#247]
On FreeBSD the definition of getmode [1] conflicts with the same function in the implementation of libc for us [2]. For FreeBSD the __BSD_VISIBLE macro [3] exposes getmode. 

The compilation error can be found here [4]. To prevent the compilation errors this git diff seems to fix it  [5].

The same is needed for devio.c, fsck.c, mkfs.c and util.c.

[1] Standalone/fuzix_fs.h:315 
[2] /usr/include/unistd.h:505
[3] /usr/include/sys/cdefs.h:766-786
[4] http://dpaste.com/2Y1KSHN
[5] http://dpaste.com/17V9PCM

**Comment by EtchedPixels** [comment]
I renamed the function - avoids any future problems or finding out NetBSD, OpenBSD, Solaris or someone else has getmode() in its headers too.
