### ISSUE TITLE
Keyboard layout support

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#25]
Keyboard layout is hardcoded as QWERTY on zx128 code. I want to add Turkish F layout, but it does not fit.

**Comment by EtchedPixels** [comment]
keyboard bitmap reporting API added. UTF-8 in the keyboard driver of a Turkish machine actually looks to be fairly easy to. Make the map table 16bit UCS2 values not 8bits/char and then write 1-2 bytes according to the unicode value.

So I don't think there is an imput problem here having looked in detail. Similarly on output your vt output routine would need to assemble unicode sequences.

**Comment by erkinalp** [comment]
>Changing the keymap is easy enough but given the hardware physically only supports 40 buttons.
ZX Spectrum 128 definitely has more than forty keys on its keyboard.

**Comment by EtchedPixels** [comment]
Spectrum has 40 keys. The 128 appears to have more but they are wired in the keyboard matrix to press two buttons at once. I've actually implemented minimal unicode input support and some special encodings for byte sized keycodes to cover £ € ½.

Doing it more generally you'd just need to change your keyboard driver to generate utf-8 codes not byte ones and then queue the utf-8.

**Comment by erkinalp** [comment]
14 Oca 2015 20:37 tarihinde "EtchedPixels" <notifications@github.com> yazdı:
>
> Spectrum has 40 keys. The 128 appears to have more but they are wired in
the keyboard matrix to press two buttons at once.
>

So sad. It means we would have no means to have N-key rollover on ZX
Spectrum. Maybe up to three keys at once. I will have to consider this when
designing the Turkish keymap.

**Comment by erkinalp** [comment]
FYI, Turkish F layout is something like this:
https://upload.wikimedia.org/wikipedia/commons/5/5d/KB_Turkey_f.svg
Ç, Ğ, İ, ı, Ü, Ö, Ş are considered separate letters from their unaccented ones in Turkish. I am planning to experiment a key reduction exercise to fit on Spectrum and the like.
