### ISSUE TITLE
Problem building userspace 

### ISSUE THREAD

**Issue by gustauperez** [EtchedPixels/FUZIX#251]
According to the user space wiki, fcc and friends are needed. However the build of the syscall helper fails because of the syscall_name.h header is not in the same directory. Helping the compiler passing it the right place to search the header helped the build.

Perhaps it should be noted in the wiki or a simple Makefile may be deployed on Library/tools to build those. Or perhaps including ../../Kernel/include/syscall_name.h would do it.

[1] https://github.com/EtchedPixels/FUZIX/wiki/Building-User-Space
[2] http://dpaste.com/37BKFX7
[3] CFLAGS=-I../../Kernel/include make syscall

**Comment by EtchedPixels** [comment]
Humm works for me because Library/Makefile adds the CFLAGS

**Comment by gustauperez** [comment]
Then I guess the wiki should be updated to show that those are built from Library instead of cd Library/tools && make binman fcc fsize syscall.

**Comment by EtchedPixels** [comment]
It says "Everything here is now hopefully historical except for the notes about where the tools need to go."
