### ISSUE TITLE
libclean should use Kernel/tools/findsdcc

### ISSUE THREAD

**Issue by gustauperez** [EtchedPixels/FUZIX#252]
Building Library/tools fail both on Linux (virtual machine) with sdcc on /usr/local and with FreeBSD [1]

I think that like in commit 853bddec8, libclean [2] should use Kernel/tools/findsdcc to find the right sdcc lib path. That way (I guess) the build of the tools in Library/tools would proceed.

[1] http://dpaste.com/22Y48XG
[2] http://dpaste.com/1SBFJFF

**Comment by EtchedPixels** [comment]
hopefully now fixed
