### ISSUE TITLE
inittab

### ISSUE THREAD

**Issue by DimkaM** [EtchedPixels/FUZIX#275]
Tell me, please, where to get a working inittab?

**Comment by EtchedPixels** [comment]
Standalone/filesystem-src/etc-files/inittab

**Comment by DimkaM** [comment]
Thank you.
So the problem is not in the script.
I'll catch the bugs in my code.
"FUZIX version 0.1
Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>
Copyright (c) 2014-2015 Alan Cox <alan@etchedpixels.co.uk>
Devboot
4096kB total RAM, 3968kB available to processes (15 processes max)
Enabling interrupts ... ok.
 SD drive 0: hda:
Mounting root fs (root_dev=0): OK
Starting /init
init version 0.9.0ac#1
: is not an identifier"

**Comment by beretta42** [comment]
4 Megs of RAM?  cool!  which platform/machine has that?  MSX2?

On Sun, Oct 25, 2015 at 10:11 AM, DimkaM <notifications@github.com> wrote:

> Thank you.
> So the problem is not in the script.
> I'll catch the bugs in my code.
> "FUZIX version 0.1
> Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
> Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
> Copyright (c) 2013-2015 Will Sowerbutts will@sowerbutts.com
> Copyright (c) 2014-2015 Alan Cox alan@etchedpixels.co.uk
> Devboot
> 4096kB total RAM, 3968kB available to processes (15 processes max)
> Enabling interrupts ... ok.
> SD drive 0: hda:
> Mounting root fs (root_dev=0): OK
> Starting /init
> init version 0.9.0ac#1
> : is not an identifier"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EtchedPixels/FUZIX/issues/275#issuecomment-150926741>.
>



-- 
Brett M. Gordon,
beretta42@gmail.com

**Comment by DimkaM** [comment]
http://nedopc.com/zxevo/zxevo_eng.php

**Comment by EtchedPixels** [comment]
one thing to check is to delete inittab. init should then just load the shell up. That may help find the bug.

**Comment by DimkaM** [comment]
По вашему совету, удалил inittab.
Ошибка осталась.
Буду копать, где проблема.

Извините, я использую googletranslate

**Comment by DimkaM** [comment]
On your advice, I removed inittab.
The error remained.
I will dig, where the problem is.

Sorry, I use googletranslate

**Comment by DimkaM** [comment]
I am a disabled driver a ps/2 keyboard. An error has disappeared.
The problem in my keyboard driver.
I will try to enter characters via the rs232.
