### ISSUE TITLE
Test SIGCONT, SIGSTOP handling

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#283]

**Comment by EtchedPixels** [comment]
Logic put in place for the basics (SIGSTOP, SIGCONT) without TSTP or job control. Needs testing done

**Comment by beretta42** [comment]
Initial test of SIGSTOP panic()'s on an infinite loop:

_chksigs() calls psleep() on pending SIGSTOP
psleep() calls switchout()
switchout() calls _chksigs()  (and starts the infinite loop)

I temporarily disabled the call to _chksig() in my tricks.s (coco3)  and SIGSTOP and SIGCONT seem to behave better.

**Comment by EtchedPixels** [comment]
On Thu, 25 Feb 2016 08:53:35 -0800
"Brett M. Gordon" <notifications@github.com> wrote:

> Initial test of SIGSTOP panic()'s on an infinite loop:
> 
> _chksigs() calls psleep() on pending SIGSTOP
> psleep() calls switchout()
> switchout() calls _chksigs()  (and starts the infinite loop)

Ick.. hacky change pushed

**Comment by beretta42** [comment]
It is still broke.  psleep() sets it's process to P_SLEEP before (re)calling _chksig.  :(

https://github.com/EtchedPixels/FUZIX/blob/master/Kernel/process.c#L39

**Comment by EtchedPixels** [comment]
Sigh. I'll have a look at exactly what is supposed to happen first, then worry about a correct fix.

**Comment by beretta42** [comment]
I'm in no rush.  I'll keep on testing the newer level two stuff.

**Comment by EtchedPixels** [comment]
Had another quick go at this in my break
