### ISSUE TITLE
login to reset terminal ?

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#302]
Should login/init reset its terminal before attempting next login ?

**Comment by EtchedPixels** [comment]
Yes

**Comment by erkinalp** [comment]
login should, init should not.

**Comment by EtchedPixels** [comment]
In the fuzix case that isn't true because getty is effectively part of init.

**Comment by beretta42** [comment]
Ah.. this makes sense.  Maybe reset terminal in the getty part of init
then. :) With a stern warning not to shuffle the reset to the init part. ?

Brett M Gordon

**Comment by EtchedPixels** [comment]
Done along with baud rate options and  few others
