### ISSUE TITLE
Code accidentally put in .data section (coco3)

### ISSUE THREAD

**Issue by vandys** [EtchedPixels/FUZIX#310]
Code reading coco3.s, scrPos is put in .data, but the following routine
map_for_swap would appear to also be put in .data because there
was no "area .text" following the scrPos definition?

**Comment by beretta42** [comment]
Yup... that's an error. Good catch.  It should be in .common.  Not sure if this function/routine gets called (yet), so it shouldn't be an immediate problem, but I'll submit a commit asap.
