### ISSUE TITLE
Feature: TI-89/92/etc support

### ISSUE THREAD

**Issue by sweisman** [EtchedPixels/FUZIX#317]
I first read about this project when it was launched. I thought it was only ever going to be a Z80 OS, so it's cool to see the porting to other CPUs. If 68K support already exists, the TI-92 seems like a suitable device to port this too. While technically a calculator, it is a full 68K computer with a full Qwerty keyboard (the TI-89 is basically the same device in a calculator form factor).

The 92+ variant has a 12MHz 68000, 256KB RAM and 2MB flash ROM (the Voyage 200 version has 4MB). Someone made an attempt to create a Unix-like OS for this platform (see Punix - http://punix-os.blogspot.com/), but gave up after a time.

**Comment by EtchedPixels** [comment]
Some early 68K bits have been done.If you want 92+ support then hack on it. I'm not planning to get back to 68000 support for a while yet - need to do networking, finish job control, get the PCW8256 port up and running etc first.
