### ISSUE TITLE
bug: core dump "fails" on 6809

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#320]
Call stack:
 dump_core() in process.c
 write_core_image() in syscall_exec16.c
 newfile() in filesys.c
 ch_link() in filesys.c
 writei() in inode.c

ch_link() returns error in line 332, as udata.u_error is set from some previous syscall to 4 (EINT).  No failure is actually happening in writei(), but it looks that way to ch_link(). Core dumping works if I do this in ch_link():

@ 326 in filesys.c
+   udata.u_error = 0;
    udata.u_count = DIR_LEN;
    udata.u_base  = (unsigned char*)&curentry;
    udata.u_sysio = true;
    writei(wd, 0);

    if(udata.u_error)
        return false;

I'm not sure if resetting u_error is a good thing. Just prior to this code ch_link() also calls readi(), and makes the same u_error assumption.

**Comment by EtchedPixels** [comment]
On Wed, 02 Mar 2016 06:38:00 -0800
"Brett M. Gordon" <notifications@github.com> wrote:

> Call stack:
>  dump_core() in process.c
>  write_core_image() in syscall_exec16.c
>  newfile() in filesys.c
>  ch_link() in filesys.c
>  writei() in inode.c
> 
> ch_link() returns error in line 332, as udata.u_error is set from some previous syscall to 4 (EINT).  No failure is actually happening in writei(), but it looks that way to ch_link(). Core dumping works if I do this in ch_link():
> 
> @ 326 in filesys.c
> +   udata.u_error = 0;
>     udata.u_count = DIR_LEN;
>     udata.u_base  = (unsigned char*)&curentry;
>     udata.u_sysio = true;
>     writei(wd, 0);
> 
>     if(udata.u_error)
>         return false;
> 
> I'm not sure if resetting u_error is a good thing. Just prior to this code ch_link() also calls readi(), and makes the same u_error assumption.  

If you add udata.u_error = 0 to the top of write_core_image() then that
ought to be right I think. Basically "write_core_image" is as if we
started a new syscall in all but name.

Alan
