### ISSUE TITLE
init: CTTY, utmp not always set properly

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#331]
This is the bug: 

https://github.com/EtchedPixels/FUZIX/blob/master/Applications/util/init.c#L668

This frees the space used by the in-memory inittab + initpid. This brk-alloced mem is where the strings for the tty and ID sit.  A few lines later the calls to envset() attempt to copy ttyname over itself (well, now it's a env string).   If I comment out line 668, all works well.  (yay!  I can use "more" from tty1)

Not sure what the consequences of not releasing this memory is, though.  If the memory really needs to be released, then maybe copy ttyname and ID to temp buffers first. ???

**Comment by EtchedPixels** [comment]
facepalm

Yeah easiest not to bother releasing it - for now anyway
Fixed
