### ISSUE TITLE
in_group() called in level 1 code

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#335]
https://github.com/EtchedPixels/FUZIX/blob/a31db315645b286a5f1f0901b8c63668a7e57a15/Kernel/syscall_fs2.c#L248

prevents compiling on level 1 platforms.

**Comment by beretta42** [comment]
init.c also fails to compile, as initgroups() is not made in 6809 lib's makefile.

**Comment by EtchedPixels** [comment]
Fixes pushed. Should be ok now but not tested them all
