### ISSUE TITLE
Support from NEC PC 8bit Series.

### ISSUE THREAD

**Issue by keito940** [EtchedPixels/FUZIX#400]
Supporting Japanise Personal Computer System.
#  Main Model 
## PC-8801 mkIISR 
* 512 color.  
* One Palette 8 Color.  
* FM Sound. (YM2203(OPN))
  
# Sub Model
##  PC-8001 mkII(First Japanise Computer.)  
* 8 Color.  
* One Palete 4 Color.

**Comment by EtchedPixels** [comment]
There are lots of machines it would be good to support, these included. If you want to contribute patches please do so.
