### ISSUE TITLE
panic: corrupt inode, when trying to create a file in a non-existent directory

### ISSUE THREAD

**Issue by dfffffff** [EtchedPixels/FUZIX#407]
when trying to create a file in a non-existent directory I get a kernel panic

```
# touch /dsfdsf/dsff

panic: corrupt inode
```

**Comment by EtchedPixels** [comment]
duplicated here.. humm

Specific to open so I suspect breakage from some of the open re-arrangement that went on.

**Comment by EtchedPixels** [comment]
Fixed
