### ISSUE TITLE
coco2cart extra large swap partitions

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#468]
https://github.com/EtchedPixels/FUZIX/blob/master/Kernel/platform-coco2cart/discard.c#L80

This 128 block offset gets multiplied by SWAP_SIZE to get the final block no.  Yielding a 5.2 MB size.  Maybe this offset can be post scalar, in  swap_out() in simple.c ?

**Comment by EtchedPixels** [comment]
There's no reason to make it post scaling. We are going to need one bank for kernel image so we could just start it at 1 not 128. Or if we add partition support to mini_ide/sdc then it goes away.
