### ISSUE TITLE
Porting Java&C#&Python Language. (And More.)

### ISSUE THREAD

**Issue by keito940** [EtchedPixels/FUZIX#495]
Java And C#.
Java is a programming language with C++ usability added to Objective-C ported Smalltalk-VM to C language.
In addition, C# is a programming language that contains elements of Java and C++ in Delphi which is a Pascal processing type used in Windows. Because there are things that Delphi former staff and Windows selling agency are making, it is getting familiarity with Windows and cross platform.
And the language Python is establishing its status as a split language.
So, can you port Python and Java or C#?
Even as it is the lightness of FUZIX as it is.
...And Porting D Programming Language.

**Comment by beretta42** [comment]
Sounds cool... I bet Alan would say: "sure! you send the patches in"   :)

**Comment by EtchedPixels** [comment]
yep
