### ISSUE TITLE
'reboot' command leaving fs dirty.

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#535]
After a clean boot, issue 'reboot' command, the second boot reports a dirty fs.

**Comment by EtchedPixels** [comment]
If you mounted the file system read/write then I'd expect that.

What occurs with

bootdev: whatever ro
halt

and with

bootdev: whatever
...
remount /dev/whatever ro
halt

??

**Comment by beretta42** [comment]
Oh duh... i was expecting sync() to safely store super... but that doesnt do that...
