### ISSUE TITLE
util/fsck: fails on rebuilding freelist

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#539]
Something about rebuilding the freelist wonks out the filesystem where pass 3 is concerned... a fresh filesystem passing /standalone/fsck, finds many, many, many multiply linked blocks in pass3 of /util/fsck :(

**Comment by EtchedPixels** [comment]
The two versions are basically the same code. I think you may need to have words with your gcc again 8)

**Comment by beretta42** [comment]
Still debugging this.  it seems the inode get fudged up by pass 2.  Everythings orderly until i get to a wacky inode with obviously wrong block allocation...  block 0xbd30 is alloced twice (in same inode)..  'bd' is cpu's 'jsr'.

**Comment by beretta42** [comment]
Tracted issue down to an overflow error in the drivewire driver... /dev/devdw.c and /platform/drivewire.s overflow when converting 512 byte blocks to 256 byte blocks.  A max sized fs will aslpode.
