### ISSUE TITLE
Collaboration with projects targetting 8/16BIT systems?

### ISSUE THREAD

**Issue by timofonic** [EtchedPixels/FUZIX#545]
Hello.

Any hopes to see collaboration with other projects?

What about @SirCmpwn @KnightOS?

Sny other projects that may be willing to collaborate?

**Comment by EtchedPixels** [comment]
SDCC, cc65, Z80Pack, retrobrewcomputers, lwtools and plenty of others. Plus of course lots from the historic unix v7 and coherent trees.

**Comment by timofonic** [comment]
@EtchedPixels Thanks for the info!
