### ISSUE TITLE
irc

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#547]
Needs to understand \001ACTION text\001  (/me blah) and maybe generate it
Also some of the other \00x codes want filtering I think

**Comment by beretta42** [comment]
mind if i also add vt52 nickname coloring.  And format sent channel messages in the same format as recv messages?

**Comment by EtchedPixels** [comment]
Sounds good but we need to be careful about size - it is a tight fit on a 32K bamk when built Z80
