### ISSUE TITLE
Support networking without Level 2

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#550]
We'll need this on some machines, particularly slower ones. Quite a lot of our networking tools don't it turns out need select() so there is no reason to tie them together.

**Comment by beretta42** [comment]
I think you already untied it?  I bumped the coco3 port down to level one a while ago to test Level one (no select) networking.  I seems to work fine without level two stuff.

**Comment by EtchedPixels** [comment]
Duh so we did somewhen
