### ISSUE TITLE
More docs: Porting manual

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#564]
Something like that, for `fuzix`:
http://www.tldp.org/LDP/cpg/Custom-Porting-Guide.pdf

**Comment by EtchedPixels** [comment]
It does need to exist - but the problem is that we are still at the point where by the time it was written it would be out of date because stuff is changing quite fast in the core as I try and add 68000, 65C816 and 8088

**Comment by EtchedPixels** [comment]
Docs slowly congealing
