### ISSUE TITLE
'killall' kills itself.

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#573]
"killall" sends a sig to pid 0, killing its process group.  Not sure how its getting a 0 pid from /dev/proc... i assumed killing something else modifies the ptabs while killall is still iterating.. and returns an empty ptab for the last entry.  Maybe we need to iterate and build a list of pids, then iterate overthat list killing things.  ?

**Comment by EtchedPixels** [comment]
Probably I'm doing something stupid like killing process slots marked as empty 8)
Will take a look

**Comment by EtchedPixels** [comment]
#facepalm
