### ISSUE TITLE
fork() and runticks

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#581]
When we fork the effect is that the parent gets the boot and the child gets a new runticks thus schedule cycle. That appears to be unfair. Should we in fact just leave runticks when we fork() and properly punish someone for that expensive work - or is the unfairness actually better for performance ?

**Comment by erkinalp** [comment]
Unfairness is better because it will make the scheduler simpler and less bugs to hunt.

**Comment by beretta42** [comment]
If we're usually forking just to wait() then the child getting the remaining slice is probably a good thing?

**Comment by EtchedPixels** [comment]
Right now the child gets a full slice
