### ISSUE TITLE
Remounting root ro fails

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#593]
the kernel's umount call checks for writers and on-disk link count for 0, otherwise it fails:

https://github.com/EtchedPixels/FUZIX/blob/master/Kernel/syscall_other.c#L398

In my particular case, "/etc/mtab" is the culprit inode that's bombing out umount(). The kernel is reporting no writers on the file, and is returning a nlink of 1.  Should the 'remount' utility be unlinking /etc/mtab before trying to umount() it?  Or maybe umount() should have the OR logic flipped to AND logic or something?

**Comment by beretta42** [comment]
Hmm... maybe we're catching the defunct inode.  Should a check for the inode actually being valid be done as well?

**Comment by beretta42** [comment]
Nah.  That code is right.  Something is holding c_refs open on /etc/mtab.  I suppose it is during 'remount' is when this is all happening.  maybe rename() needs checked.

**Comment by beretta42** [comment]
yup.  rename() was holding on to dsti.  This seems to work: 

`https://github.com/beretta42/FUZIX/commit/12ba565a34c94b321fabb89070f486a1321142be`

Although I don't trust my understanding here enough to do a PR and know I wouldn't be screwing things up worse :)

**Comment by EtchedPixels** [comment]
Fixed I think ?

**Comment by beretta42** [comment]
Yes.   seems to be in order
