### ISSUE TITLE
tar doesn't O_TRUNC new files

### ISSUE THREAD

**Issue by davidgiven** [EtchedPixels/FUZIX#601]
...leading to hilarious results if the file already exists and has content longer than the original.

**Comment by beretta42** [comment]
there is a couple of tars in the repo.  Which one?

**Comment by davidgiven** [comment]
`Applications/util/tar.c`, I think (judging by the errors messages I was getting). (I just typed 'tar'.)

**Comment by beretta42** [comment]
Yeah. :( That's my butcher job. both issues seem fixable, though.

**Comment by davidgiven** [comment]
I'd do it myself, but I couldn't figure out how to make the userland build.

**Comment by EtchedPixels** [comment]
Userland build should work with

Install sdcc

cd top directory
Make sure you've got 16GB of RAM+swap
set TARGET=z80pack
make
