### ISSUE TITLE
returning from main doesn't propagate the exit code on Z80

### ISSUE THREAD

**Issue by davidgiven** [EtchedPixels/FUZIX#603]
false uses an explicit exit(1), but true just does return(0):

```
# true; echo $?
245
# false; echo $?
1
```

What's happening is that crt0.s is pushing _exit onto the return stack, so it gets called automatically on exit, but the value returned by main() is left in HL but is expected to be on the stack. It's going to need a trampoline to make this work.

**Comment by EtchedPixels** [comment]
Duh fixed
