### ISSUE TITLE
Applications/util: cal.rel: Multiple definition of _timezone FTBFS

### ISSUE THREAD

**Issue by piso77** [EtchedPixels/FUZIX#621]
Fresh build (HEAD: 'f5ee69c binman: Fix crash with oversized binaries'):

...
../../Library/tools/fcc -mz80  -O2 -c cal.c
cal.c:193: warning 84: 'auto' variable 'year' may be used before initialization
cal.c:195: warning 84: 'auto' variable 'year' may be used before initialization
cal.c:197: warning 84: 'auto' variable 'year' may be used before initialization
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
cal.c:353: warning 196: pointer target lost const qualifier
../../Library/tools/fcc -mz80   cal.rel -o cal
Multiple definition of _timezone
Makefile.z80:145: recipe for target 'cal' failed
make[2]: *** [cal] Error 1
make[2]: Leaving directory '/home/flag/FUZIX/Applications/util'
Makefile:10: recipe for target 'util' failed
make[1]: *** [util] Error 2
make[1]: Leaving directory '/home/flag/FUZIX/Applications'
Makefile:61: recipe for target 'apps' failed
make: *** [apps] Error 2

flag@harukaze:~/FUZIX/Applications/util$ ../../Library/tools/fcc -mz80   cal.rel -o cal
Multiple definition of _timezone

flag@harukaze:~/FUZIX/Applications/util$ grep -i timezone cal.rel 
S _timezone Def008B
flag@harukaze:~/FUZIX/Applications/util$ grep -i time cal.rel 
S _time Ref0000
S _localtime Ref0000
S _timezone Def008B
S _time_zone Def0089

**Comment by EtchedPixels** [comment]
Seems to depend on the sdcc but yes it's a bug - fix pushef
