### ISSUE TITLE
platform-z80pack/createdrives – BASHisms in SH script?

### ISSUE THREAD

**Issue by drawkula** [EtchedPixels/FUZIX#644]
https://github.com/EtchedPixels/FUZIX/blob/bbe58dd63ef18971fd584240f9e4efe9f7fb6607/Kernel/platform-z80pack/createdrives#L62

The `#!/bin/sh` script uses `&>` which is not understood as intended by Debian9's `sh`.

**Comment by EtchedPixels** [comment]
Obsolete script - so removed it 8)
