### ISSUE TITLE
Build of target trs80m1 fails

### ISSUE THREAD

**Issue by ghost** [EtchedPixels/FUZIX#650]
with:
```
../../../Library/tools/fcc -mz80 -ttrs80m1  dc.rel -o dc
error: size of the buffer (65535 bytes) is too small for 65536 bytes.
Makefile.z80:50: recipe for target 'dc' failed
```
(Modified `makebin` of `sdcc` to show the values)

**Comment by EtchedPixels** [comment]
I don't plan to fix this until I have relocatable binary support - simply because at that point the problem goes away anyway, and it becomes just a runtime limit. Getting dc into 32K is a different project.

**Comment by EtchedPixels** [comment]
Relocatable binaries are now turned on so this bug goes away. Instead a few binaries will correctly refuse to run on the smaller systems.
