### ISSUE TITLE
startrek install: missing/misnamed file

### ISSUE THREAD

**Issue by beretta42** [EtchedPixels/FUZIX#673]
build-filesystem is failing on startrek:
1. packager is trying to install "startrek.info" as "startrek.intro"
       * not sure if file name is wrong in startrek.c or in applications/games/fuzix-games.pkg
2. packager is trying to install "startrek.fatal" and it doesn't exist yet

**Comment by EtchedPixels** [comment]
Must have been asleep when I made those changes 8)
Fixed I think
