### ISSUE TITLE
dc takes too long and too much memory to compile

### ISSUE THREAD

**Issue by jayacotton** [EtchedPixels/FUZIX#677]
Fresh install of source code.
Edit the Kernel/platform-rc2014/config.h
and ~/Makefile to rc2014.

on my machine I need to say...
sudo make j=4  (can't install the tools). :(

Then in the applications directory it stalls at dc.o  I just never finishes the build.  hangs for long time.

**Comment by EtchedPixels** [comment]
Closing as this is an sdcc issue
