### ISSUE TITLE
Configure for ppide gets build error.

### ISSUE THREAD

**Issue by jayacotton** [EtchedPixels/FUZIX#678]
With this Kernel/platform-rc2014/config.h

/* System level configuration */

/* Set this if you have the RC2014 CF adapter at 0x10/0x90 */
#undef CONFIG_RC2014_CF
/* Set this to be able to do networking over the second serial port */
#undef CONFIG_RC2014_NET
/* Set this if you have the 8255 IDE adapter (mutually exclusive of RC2014_CF) */
#define CONFIG_RC2014_PPIDE
/* Set this if you have the floppy interface */
#undef CONFIG_RC2014_FLOPPY
/* Set this if you have a VFD interface */
#undef CONFIG_RC2014_VFD

-------------------------snip ------------------------------------------
I get these errors.

make[2]: Leaving directory '/home/jay/projects/fuzix/FUZIX-master/Kernel/tools/bankld'
tools/bankld/sdldz80 -n -k /usr/local/share/sdcc/lib/z80 -f platform-rc2014/fuzix.lnk

?ASlink-Warning-Undefined Global '_devide_read_data' referenced by module 'devide'

?ASlink-Warning-Undefined Global '_devide_read_data' referenced by module 'devide_discard'

?ASlink-Warning-Undefined Global '_ppide_init' referenced by module 'discard'

?ASlink-Warning-Undefined Global '_devide_write_data' referenced by module 'devide'

?ASlink-Warning-Undefined Global '_devide_readb' referenced by module 'devide'

?ASlink-Warning-Undefined Global '_devide_writeb' referenced by module 'devide'

?ASlink-Warning-Undefined Global '_devide_writeb' referenced by module 'devide_discard'
make[1]: *** [cpu-z80/image.mk:43: fuzix.ihx] Error 2
make[1]: Leaving directory '/home/jay/projects/fuzix/FUZIX-master/Kernel'
make: *** [Makefile:79: kernel] Error 2

**Comment by c32ff0** [comment]
Quick fix again, add this line at the end of Kernel/platform-rc2014/fuzix.lnk (before the -e )
```
platform-rc2014/ppide_rbc.rel
```

**Comment by EtchedPixels** [comment]
Patch applied

**Comment by jayacotton** [comment]
That works for me now.  Thanks
