### ISSUE TITLE
How do you set termcap for levee ?

### ISSUE THREAD

**Issue by jayacotton** [EtchedPixels/FUZIX#681]
Been trying all kinds of stuff, and no luck.  How do you set it ?  What is default and how do you get minicom to play nice with it.

**Comment by EtchedPixels** [comment]
TERM=vt100
export TERM

or similar should work for any terminal in the termcap file.

**Comment by jayacotton** [comment]
Ah, no $ .....

**Comment by jayacotton** [comment]
I ended up by changing the vi link to levee-ansi and adjusting minicom to ansi.
now working.
