### ISSUE TITLE
yaz180 - missing stdint.h etc

### ISSUE THREAD

**Issue by feilipu** [EtchedPixels/FUZIX#693]
I noticed that the following files are not present in `/opt/fcc/include`, which stops the build.
`stdint.h` `stddef.h` and `stdarg.h`.

I copied those files present in `~/FUZIX/Library/include/8080` across to `/opt/fcc/include` manually, and that allowed the build to proceed. I guess these are accurate enough, as there didn't seem to be a specific z80 or z180 set available.

**Comment by EtchedPixels** [comment]
It should be finding them from the standard SDCC search path

**Comment by feilipu** [comment]
Yes. My problem.

I had configured my SDCC build as if it was ZSDCC and hadn't compiled the standard libraries.
