### ISSUE TITLE
Z80 external memory protection unit

### ISSUE THREAD

**Issue by retrac0** [EtchedPixels/FUZIX#744]
I think it might be possible to build an MMU with memory paging and memory protection for the Z80, using not that many 74xx type chips:

- The MMU has a flip-flop that creates an internal user/kernel mode.  (1 flip flop)
- It presents four page/bankswitch registers and one control register in the IO space.  (4 8 bit registers, 1 flip flop) 
- In each mode, two 32 KB banks are available, which may point to any 32 KB chunk of memory.  With 8 bit registers, that's up to 8 MB of addressing.
- The MMU also gates certain bus signals, as well as the data bus. (5 - 10 gates?)
- In user mode, IO instructions are effectively disabled by gating the IOREQ signal. (2 gates?)
- In user mode, the IM 0, IM 1, IM 2, and DI opcodes when read from memory are are transformed into NOPs on the bus when M1 is active indicating an opcode fetch.  This prevents userspace programs from messing with interrupts.  (20 - 30 gates?)

- Upon interrupt acknowledgement (IOREQ + M1), we switch to kernel mode.  I think the easiest thing after this is to use interrupt mode 0, and to force some opcode bytes on the bus.  (???)
- Do code that saves the machine state somehow, stack save to known kernel page address, set stack to known location, then call/RST into a kernel routine to handle interupts.  Pretty sure this is possible, but maybe I'm missing some subtle loss of state? 
- When we reenable user mode from kernel mode, the only way back is via external hardware interrupt, so maybe something like IO writes in user mode will trigger it too to allow a software interrupt path.

I'm submitting this here because Fuzix seems about the only thing that could ever use memory protection on a Z80.  It seems at least feasible, if a bit tricky, from a hardware perspective.  But aside from that, does this work from a programming perspective?

**Comment by EtchedPixels** [comment]
There were several S100 boards that did this towards the end but it's actually a good deal more complicated.  Many boards simply supported write protected ranges (eg common) which is actually really useful - especially if it NMIs. Some Sinclair clones/add ons also support doing switching with NMI by switching to a given bank on NMI and switching back on the return path. In fact the 'easy' way of dealing with interrupts that some of these systems used was to route interrupts to NMI via an external interrupt controller. Now EI/DI/IRQ/IM* don't matter. In fact you can even use them for 'user level' interrupts and your real DI/EI are out's to a controller (protected by the IORQ gate)

The fancy ones though also have to deal with the stack. When you take an interrupt the CPU wants to push the user stack pointer, but that could be pointing to any address so you can't simply switch bank on interrupt. Instead you actually have to time it all from the bus cycles. You also have to make it back nicely which means you need a thing you poke that changes privilege mode 'n' instructions after.

You also need a way to trap from user to kernel of course.

It might be fun to recreate one of the S100 implementations used to run things like Micronix but the stuff I've found tends to use PALs and similar and the schematics are incomplete and don't usually include the equations.

Take a look at the InterSystems XPU-80 docs, or the Morrow MPZ80 documentation.

http://www.s100computers.com/Hardware%20Folder/Intersystems/Series%20III%20Z80/IA%20Z80-IIII.htm

https://archive.org/details/bitsavers_morrowsche80_549770
