### ISSUE TITLE
Adventures look to be off by one on screen height

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#747]

**Comment by tormodvolden** [comment]
Doesn't look to bad here on dragon-mooh, at least when it comes to the prompt. There is an extra newline printed after my entries but I don't know if that is intended.
![adv01-32x24](https://user-images.githubusercontent.com/2403928/65449413-3ed39080-de3b-11e9-89ea-b5a1a2d52237.png)
![adv01-32x16-libcuss](https://user-images.githubusercontent.com/2403928/65449423-42671780-de3b-11e9-95e6-b42ae37ed592.png)
The "<@>" line is meant to be a separator between upper and lower "window"? I think something like "===" would be nicer.

Would be nice to have some easy-to-run test cases, for verifying vt52 emulation, termcap, etc. I see some oddities in vile and levee but I don't know if it is the application or display layers.

**Comment by EtchedPixels** [comment]
The blank line is intended. I am wondering if Brett had the screen height off by one

**Comment by beretta42** [comment]
Hmm.. I'll check.  I sorta remember there's some window size api that i never hooked up on the coco3.

**Comment by tormodvolden** [comment]
BTW, for the issues I see in vile, I see the same when I compile it for Linux, so it is the application.

**Comment by EtchedPixels** [comment]
I think vile is a different set of issues so I am closing this now it seems to be working

There *are* a bunch of other bugs related to word wrapping etc that I do need to tackle and am working on sorting out. I may write myself a split window adventure game library and just stick it all in one place - we shall see
