### ISSUE TITLE
Z80: Clearing SP required before using?

### ISSUE THREAD

**Issue by kmorimatsu** [EtchedPixels/FUZIX#750]
I'm using Tom's SBC (EPROM based; ver 0.3) in an emulator:
https://kmorimatsu.github.io/fuzix/fuzix.html
https://kmorimatsu.github.io/fuzix/help/english.html

In this Kernel, Z80 stack pointer is first used at address 0x0053 (as CALL statement) before initialization. Probably most Z80 emulators clear SP (to 0x0000) at reset, but according to datasheet of Z80 CPU, it doesn't (only PC and registers I, R, and IM are cleared). Initialization of SP would be needed in the beginning of Kernel for some Z80 environment.

**Comment by EtchedPixels** [comment]
Luckily the Z80 always sets AF and SP to FFFF on power up. I will check this out and fix it though because it is not documented Z80 behaviour.

Thanks
