### ISSUE TITLE
"ln -s" doesn't seem to work

### ISSUE THREAD

**Issue by jes** [EtchedPixels/FUZIX#751]
When I try to make a symlink using `ls`, I just get given usage instructions.

For example:

```
# ln -s /bin/more /bin/less
Usage: ln [-f] [-n] [-s] f1 f2
       ln [-f] [-n] [-s] f1 ... fn d1
       ln [-f] [-n] [-s] d1 d2
```

**Comment by jes** [comment]
So from the comment at the top of Applications/util/cp.c it looks like it's not meant to handle symlinks, so I think just the documentation of "-s" needs to be removed.

**Comment by jes** [comment]
https://github.com/jes/FUZIX/commit/4d3b6e92e6cf7814e69abac2034bc6bbd8016889

**Comment by EtchedPixels** [comment]
Applied, thanks

There is indeed no symlink support in Fuzix and it would be difficult to squash into the 8bit ports.
