### ISSUE TITLE
vi is confused by tabs

### ISSUE THREAD

**Issue by jes** [EtchedPixels/FUZIX#753]
The presence of a tab character seems to confuse vi's rendering.

Steps to reproduce: run vi, enter insert mode (i), type a single tab, and then start typing a sentence. Half the letters are missing.

It is presumably unaware that a tab is 8 spaces, although I don't quite have a mental model that explains why half the letters show up and the other half don't.

**Comment by EtchedPixels** [comment]
Not too surprised - vi is very much a work in progress!

**Comment by EtchedPixels** [comment]
Now fixed
