### ISSUE TITLE
SC126 - loadfirst & rotate

### ISSUE THREAD

**Issue by jcw** [EtchedPixels/FUZIX#759]
I'm getting some build errors on platform-sc126, looks like it's missing LOADFIRST and ROTATE definitions. I can try the definitions from `platform-rc2014/kernel.def`, but not sure the I/O bits are compatible.

BTW, this for trying out FUZIX on an SC130, which has no LEDs (shrug), but also no built-in RTC. Will this be an issue? As far as I can tell, ds1302.asm will check for presence of the chip on I2C.

**Comment by EtchedPixels** [comment]
Should do - it's somewhat up in the air at the moment as I'm working on various SC126 things with SPI and networking.
