### ISSUE TITLE
bootup service configuration

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#76]
Most inits have a way to set up boot up services in either the imperative (shellscripts) or the declarative way. FUZIX init lacks this. I had made a PR about this along with a security patch on login #70.

**Comment by EtchedPixels** [comment]
Yes I need to switch to a proper init/getty/login at some point, perhaps the ELKS ones.

**Comment by EtchedPixels** [comment]
SYS5 style init support now present, but probably in need of a little bit of a shakedown, telinit and boot time init level passing

**Comment by erkinalp** [comment]
Still needs work. systemd will not work in this state :grin:
