### ISSUE TITLE
z80pack - 0049_switchin: FAIL

### ISSUE THREAD

**Issue by Qcraft** [EtchedPixels/FUZIX#761]
I am trying to run fuzix on z80pack

Here is how i created the disk images:

`dd if=bootblock.bin of=drivea.cpm conv=notrunc`
`dd if=fuzix.bin of=drivea.cpm bs=1 seek=193024 conv=notrunc`

`./build-mini-filesystem  drivei.cpm 64 2880`

and here is the output of ./cpmsim:

`FUZIX version 0.4pre1`
`Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza`
`Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha1`
`Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>`
`Copyright (c) 2014-2019 Alan Cox <alan@etchedpixels.co.uk>`
`Devboot`
`484kB total RAM, 420kB available to processes (15 processes max)`
`Enabling interrupts ... ok.`
`bootdev: 0`
`Mounting root fs (root_dev=0, ro): OK`
`Starting /init`
`init version 0.9.0ac#1`
`Checking root file system.`
`0049_switchin: FAIL`

`panic: MMU trap/bad stack`
`Op-code trap at c916 ed 81`

Am I doing something wrong?

**Comment by EtchedPixels** [comment]
Probably not - the head of the tree hasn't been tested on z80pack

**Comment by Qcraft** [comment]
Ok, so I should just wait for 0.4?

What happened to the 0.3 tag?

**Comment by EtchedPixels** [comment]
Fixed
