### ISSUE TITLE
6809 exec changes broke stuff

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#771]
So says @beretta42 and I don't want to lose the fact this needs fixing.

**Comment by beretta42** [comment]
Its a moving bug.. the minute i put a printf in sh it errors at a different spot. Yay.  I'm still perusing syscall debug output, but not seeing anything too exciting (yet)  init seems ok, it spawns login and takes 'root' dump motd, etc.

**Comment by EtchedPixels** [comment]
That's what I'd expect to see if it's getting the binary loading wrong 8(

More useful might be to make the kernel dump the addresses of the top of code, data, bss, stack pointer for an old working tree and the current one.

**Comment by EtchedPixels** [comment]
I've pushed a fix I think for this. The crt0 code didn't include the header in the code size which in turn meant that the bss started overlapping the last 18 bytes of the data segment and things went down the pan from there.

**Comment by beretta42** [comment]
:( still dying as before:
![Screenshot at 2020-03-30 16-40-35](https://user-images.githubusercontent.com/11900832/77959894-5afe3180-72a5-11ea-8a39-3740aa030f6c.png)

**Comment by beretta42** [comment]
Sorry it took a while.  Real life's been distracting.
