### ISSUE TITLE
What's the matter with fuzix.org?

### ISSUE THREAD

**Issue by tinkercnc** [EtchedPixels/FUZIX#773]
It's offline.
I got a NC100 and wanted download the image...
:(

**Comment by EtchedPixels** [comment]
Phone engineers were seen nearby ... it's kind of limping along a bit now but waiting the ADSL to get fixed.

**Comment by tinkercnc** [comment]
OK, good to hear that's no covid, nowitschok or similar...
\</panik\>
;)

And thanks for that cool piece of software.
