### ISSUE TITLE
[PATCH] platform-sc126: missing fuzix.lnk

### ISSUE THREAD

**Issue by KatolaZ** [EtchedPixels/FUZIX#777]
While trying to compile for sc126, I noticed that fuzix.lnk is missing in folder Kernel/platform-sc126. As a result I get the following:

make[2]: Entering directory '/home/katolaz/rc2014/EtchedPixels/FUZIX/Kernel/platform-sc126'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/katolaz/rc2014/EtchedPixels/FUZIX/Kernel/platform-sc126'
make[1]: *** No rule to make target 'platform-sc126/fuzix.lnk', needed by 'fuzix.ihx'.  Stop.
make[1]: Leaving directory '/home/katolaz/rc2014/EtchedPixels/FUZIX/Kernel'
make: *** [Makefile:89: kernel] Error 2

I noticed platform-sc126 is the only platform to lack a fuzix.lnk. I adapted the  correpsonding file for sc111 (attached), by adding the sc126-specific .rel files (diff attached as well). it builds OK but I haven't tested if everything works OK. 

HTH

[fuzix.lnk.txt](https://github.com/EtchedPixels/FUZIX/files/4376166/fuzix.lnk.txt)
[diff_sc111_sc126.txt](https://github.com/EtchedPixels/FUZIX/files/4376172/diff_sc111_sc126.txt)

**Comment by EtchedPixels** [comment]
Fixed. I've pushed the missing file from my tree

**Comment by KatolaZ** [comment]
Thanks
