### ISSUE TITLE
no way to transfer files

### ISSUE THREAD

**Issue by Jonson26** [EtchedPixels/FUZIX#800]
Currently there is no real way, that I know of, to transfer files from and to a machine running FUZIX. A simple xmodem program included in the os distribution could fix that.

**Comment by beretta42** [comment]
i agree.  We could port lrzsz from gnu, or roll our own.

**Comment by retrac0** [comment]
Another option would be Kermit.  It's exceptionally portable, and E-Kermit is a pure ANSI C library that should work with a simple wrapper.  It claims 15 KB of code size on x86.

http://www.columbia.edu/kermit/ek.html

**Comment by jbquirk** [comment]
Are talking on a running system or as you building the system. If a running system yes I agree some form of serial transfer would be nice but for large files and building a new system I use a loop device under Linux and the tools are built as part of the build process.

**Comment by KatolaZ** [comment]
From a running FUZIX system you can use uud/uue and cat directly from/to the serial port (you just need uuencode/uudecode on the linux/BSD side). it's not super-handy, but definitely usable, and does not require another tool. My2Cents.
