### ISSUE TITLE
NC200  gives 'panic: no /init'

### ISSUE THREAD

**Issue by tjewell99** [EtchedPixels/FUZIX#812]
(this is related to #786, but as it seems to no longer be related to the Gotek, I thought it best to start a new issue. #786 could be closed)

I've built a boot floppy using the nc200-0.3.img supplied on fuzix.org, and a root filesystem floppy using rootfs-z80-720.img

The boot floppy works fine, gets to a bootdev: prompt. I swap floppies and enter '256'. The floppy whirrs, then gives this:

```
Mounting root fs (root_dev=256, ro): OK
Starting /init

panic: no /init
```

I rebuilt Fuzix under MacOS (that was fun!) and did a build-mini-filesystem to build a new root image. That gives the same problem. I'm a bit stuck what to try next!

**Comment by EtchedPixels** [comment]
Resolved at least when I tested
