### ISSUE TITLE
qemu and testing

### ISSUE THREAD

**Issue by ojej** [EtchedPixels/FUZIX#814]
Is possible starting without small processor?
any qemu script paramaterr for test for people?

For example I have a small procesor tomu.im and how run on it fUZIx

**Comment by EtchedPixels** [comment]
For the existing systems the RC2014 emulator and various other emulators for old systems work. I've never seriously looked at ARM and RISC-V and there is no ARM or RISC-V support in the code base at all

**Comment by Zardoz89** [comment]
qemu supports 68000 (NeXT and Machintosh Quadra emulation), so could help with 68000 support ?

https://wiki.qemu.org/Documentation/Platforms/m68k

**Comment by EtchedPixels** [comment]
The RC2014 emulators already cover tiny68k and related platforms. The Atari ST work though far from finished can also be run on Hatari or other Atari ST emulators. No need for qemu.

**Comment by ojej** [comment]
@Zardoz89 Can You show how run fuzix in qemu?

**Comment by ojej** [comment]
hello, can you show how run in emulator?

**Comment by Zardoz89** [comment]
I never try it, so I can't

**Comment by ojej** [comment]
ok
