### ISSUE TITLE
z80-mbc2: Undefined identifier 'CONFIG_RTC_INTERVAL'

### ISSUE THREAD

**Issue by pawosm-arm** [EtchedPixels/FUZIX#815]
I've came across an MBC2 board with pre-installed CP/M3 system. I've tried to build Fuzix on it, yet it failed as follows:
```
timer.c:106: error 20: Undefined identifier 'CONFIG_RTC_INTERVAL'
make[1]: *** [Makefile:127: timer.rel] Error 1
```

**Comment by EtchedPixels** [comment]
Fixed - I've not done a full test of the port with the update but it compiles again.
