### ISSUE TITLE
core1.c:7:18: fatal error: tusb.h: No such file or directory

### ISSUE THREAD

**Issue by weiqifa0** [EtchedPixels/FUZIX#839]
make[3]: Entering directory '/home/book/FUZIX/Kernel/platform-rpipico/build'
make[3]: Leaving directory '/home/book/FUZIX/Kernel/platform-rpipico/build'
make[3]: Entering directory '/home/book/FUZIX/Kernel/platform-rpipico/build'
[ 13%] Building C object CMakeFiles/fuzix.dir/core1.c.obj
/home/book/FUZIX/Kernel/platform-rpipico/core1.c:7:18: fatal error: tusb.h: No such file or directory
 #include <tusb.h>
                  ^
compilation terminated.
CMakeFiles/fuzix.dir/build.make:184: recipe for target 'CMakeFiles/fuzix.dir/core1.c.obj' failed
make[3]: *** [CMakeFiles/fuzix.dir/core1.c.obj] Error 1
make[3]: Leaving directory '/home/book/FUZIX/Kernel/platform-rpipico/build'
CMakeFiles/Makefile2:73: recipe for target 'CMakeFiles/fuzix.dir/all' failed

how to sole this problem?

**Comment by EtchedPixels** [comment]
Needs rpico sdk and the submodules for it checked out
