### ISSUE TITLE
emulator

### ISSUE THREAD

**Issue by 0xtrzy** [EtchedPixels/FUZIX#846]
Please add in web page information how runing fuzix in emulator:
qemu or other open source.

I would like to move my program but how do this?

**Comment by mrdudz** [comment]
I also tried to run it (the 6502 port) in emulator and failed to either build a working image or use the emulator correctly. Some actually working instructions that contain every step required would be really appreciated.

**Comment by sp00ck** [comment]
Please wrote small working tutorial

**Comment by zerotrzy** [comment]
documentation are important

**Comment by xor256** [comment]
I too

**Comment by EtchedPixels** [comment]
I'm slowly working through the ports fixing this a different way by adding a make target to build all the pieces the emulator needs, so it is easy to document.
