### ISSUE TITLE
Problems compiling for Amstrad NC200

### ISSUE THREAD

**Issue by tjewell99** [EtchedPixels/FUZIX#849]
Hi! I'm trying to compile the NC200 version of FUZIX. I'm using SDCC v3.5.0, patched as per the instructions.

When compiling the Kernel, it fails:

```
cc -g -O2 -Wall -Wno-parentheses -DINDEXLIB -DUNIX -I.  -o sdldz80 lk_readnl.o lkaomf51.o lkar.o lkarea.o lkdata.o lkelf.o lkeval.o lkhead.o lklex.o lklib.o lklibr.o lklist.o lkmain.o lkmem.o lknoice.o lkout.o lkrel.o lkrloc.o lkrloc3.o lks19.o lksdcclib.o lksym.o sdld.o lksdcdb.o lkbank.o
tools/bankld/sdldz80 -n -k /usr/local/share/sdcc/lib/z80 -f platform-amstradnc/nc200/fuzix.lnk

?ASlink-Warning-Undefined Global '_pagemap_add' referenced by module 'main'

?ASlink-Warning-Undefined Global '_pagemap_prepare' referenced by module 'syscall_exec16'
(snip)
make: *** [fuzix.ihx] Error 2
```

I'm using MacOS Catalina, using clang:

% cc -v
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
% sdcc -v
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8 3.5.0 #9253 (Jul  3 2021) (Mac OS X x86_64)
published under GNU General Public License (GPL)

Any thoughts? Thanks in advance!

**Comment by EtchedPixels** [comment]
Fix pushed. Forgot to update it when I updated the NC100 code
