### ISSUE TITLE
Understanding memory mapping in rc2014-6502

### ISSUE THREAD

**Issue by NollKollTroll** [EtchedPixels/FUZIX#863]
The platform rc2014-6502 uses a 512K RAM/ROM card.
Looking at loader.s & pagemap_init in main.c, I struggled to understand what the magic numbers 32/33/34/35/36 signified until I realized that the memory system has 512KiB ROM in 16KiB blocks 0-31, and 512KiB RAM in blocks 32-63.
A short paragraph describing the memory system in the platform README would make understanding it easier.

**Comment by EtchedPixels** [comment]
Added
