### ISSUE TITLE
Nuked Travis/CI integration

### ISSUE THREAD

**Issue by piso77** [EtchedPixels/FUZIX#864]
Hi Alan,

i noticed you nuked Travis recently: you didn't like Travis in particular, or you thought CI integration was just a hinder for Fuzix?

Would a move to Github actions make you reconsider CI?

**Comment by EtchedPixels** [comment]
It stopped working, it involved signing up for a load of stuff and emailing the, so I dumped it as I really didn't have time to mess with it.

**Comment by erkinalp** [comment]
One less proprietary web service to go to complete #222.
