### ISSUE TITLE
Problems Building platform-rpipico on macos

### ISSUE THREAD

**Issue by aldorgan** [EtchedPixels/FUZIX#868]
Hi!
I have problems building platfrom-rpipico on macos, i will include the error i get when making make image on pastebin: https://pastebin.com/d2VekMby

**Comment by EtchedPixels** [comment]
Not quite everything for the Pi pico is in the base tree, or merged so it works - it's close but not quite there. Probably best to build fro David Given's github tree instead right now.

**Comment by aldorgan** [comment]
Thanks for the feedback! that explains why it will not compile correctly.  i will try David Givens tree instead until it works here in the base tree.
