### ISSUE TITLE
vi/vile still writes out garbage when saving files

### ISSUE THREAD

**Issue by Spoozilla** [EtchedPixels/FUZIX#895]
[Issue 796](https://github.com/EtchedPixels/FUZIX/issues/796) was closed, however the problem with garbage being written to the end of the file still persists. I have attached a patch file that fixes the save routine, at least on my rc2014 and sc130.

[vile_patch.txt](https://github.com/EtchedPixels/FUZIX/files/7777326/vile_patch.txt)

**Comment by EtchedPixels** [comment]
I rewrote this bit properly. The old code makes some rather non portable assumptions and was horrible.
