### ISSUE TITLE
The sfdisk utility

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#90]
sfdisk is to fdisk how sed is to ed. As it has no interactive operation, its code is simpler and smaller than fdisk.

**Comment by erkinalp** [comment]
Busybox sfdisk is available under GPL1+, possible candidate: https://gitorious.org/busybox/busybox/source/ef8b6c757de9684f5d88eff4b014527e87121137:sfdisk.c

**Comment by EtchedPixels** [comment]
Our fdisk is smaller than busybox sfdisk
