### ISSUE TITLE
Is implementing 6309 native mode worthwhile?

### ISSUE THREAD

**Issue by caiannello** [EtchedPixels/FUZIX#903]
I've read with interest about the long-undocumented features of the HD6309 in "native mode":

More registers, and the ability to concatenate them to accept 16 and 32-bit words
Some instructions complete in fewer clocks vs the 6809
Several new instructions, including block transfers, hardware divide, and bit manipulations

On paper, these features seem pretty tantalizing, but most homebrew computing projects I've seen which have a 6309 on board use it 6809 compatibility mode only.  Is the real-life benefit of 6309 native mode code not worth the effort?

**Comment by EtchedPixels** [comment]
NitroOS/9 uses the 6309 support so they would be the people to ask.

For Fuzix the gcc only knows a little bit about 6309 optimisation and I don't know if -m6309 is actually usable - so mostly it  would be limited to things like assembly language hot paths or driver loops and the like.
