### ISSUE TITLE
ESP8266: "out of memory"

### ISSUE THREAD

**Issue by KedalionDaimon** [EtchedPixels/FUZIX#927]
Hi!

I compiled FUZIX, works on an ESP8266, but when I try to write a file in vi, I get an error, like this:

# vi new.c
11: out of memory by 3744
out of memory.

I CAN write text in ed, though:

# ed new.c
?new.c
this here is some text
?
a
This here is some text. I am writing it in ed.
all is funny and nice.
.
w
70
q
# cat new.c
This here is some text. I am writing it in ed.
all is funny and nice.

By the way, is there anything like a C compiler for ESP8266? The scc-compilers I see seem to be for other architectures... is there any way to program this sweet little beast beyond shell and Forth?

**Comment by EtchedPixels** [comment]
There's s very little usable memory in the ESP8266 so the stuff it can run is quite limited. Certainly no way I can see any kind of native C compiler fitting it, even small C.
