### ISSUE TITLE
Documentation Idea

### ISSUE THREAD

**Issue by madtom1999** [EtchedPixels/FUZIX#934]
I'm toying with the idea of building a stack of documentation around the FUZIX code as it strikes me as being a superb educational opportunity. I read somewhere 0.4 was in planning and would be a considerable change which would make any work on 0.3 a waste of time.
Is this true or  should I just get on with it?

**Comment by EtchedPixels** [comment]
i think most of what is there should be fairly stable for 0.4 and the core stuff is fairly stable anyway. Should find lots of bugs too 8)
