### ISSUE TITLE
DS12885

### ISSUE THREAD

**Issue by xmotif** [EtchedPixels/FUZIX#935]
Hi, I built a DS12885 board because I agree with the advantages stated on the [Hackaday page](https://hackaday.io/project/184734-rc2014-pc-style-rtc-ds12885)

Right now it looks like there is just ds12885.c/.h in the Kernel/dev directory. Is there perhaps some other unpublished prototype code? I would like to implement the ds12885 for RC2014, but first want to see if there is already some work-in-progress that I could build on.

**Comment by EtchedPixels** [comment]
That's the prototype code. I've not had time to then wire it up to stuff except test code.

**Comment by xmotif** [comment]
I've been working on it and may submit a PR this week, at the minimum for RTC function. But I would like to eventually get the interrupt timer working as well, to remove the CTC.

**Comment by xmotif** [comment]
I have some basic code to hook it up, but the DS12885 is a less than ideal timer interrupt. 64 Hz ticks are missed during disk access, causing the system time to drift. The only solution is to read the RTC during every time() system call. I still have bugs to work out.

**Comment by xmotif** [comment]
Problem with time drift has been solved by correcting logic error in plt_rtc_secs. Solving a regression with floppy driver then will submit PR.

**Comment by xmotif** [comment]
#941 fixes an issue where timer_source was being reset back to CTC every time the floppy was used.

**Comment by xmotif** [comment]
PR #942 opened for DS12885 support

**Comment by EtchedPixels** [comment]
Thanks - looks good
