### ISSUE TITLE
platform-sc126 build problem

### ISSUE THREAD

**Issue by johnwiggins** [EtchedPixels/FUZIX#955]
Building for sc126 from master, make fails with:

/home/wiggins/FUZIX/Kernel/tools/bankld/sdldz80 -n -k /usr/local/share/sdcc/lib/z180 -f platform-sc126/fuzix.lnk

?ASlink-Warning-Undefined Global '_rtc_defer' referenced by module 'devi2c'

?ASlink-Warning-Undefined Global '_ds1302_init' referenced by module 'discard'

?ASlink-Warning-Undefined Global '_ds1302_present' referenced by module 'discard'
make[1]: *** [cpu-z180/image.mk:25: fuzix.ihx] Error 2
make[1]: Leaving directory '/home/wiggins/FUZIX/Kernel'
make: *** [Makefile:114: kernel] Error 2

**Comment by EtchedPixels** [comment]
Should be fixed now. I hit the same and pushed a change
