### ISSUE TITLE
Coexistence

### ISSUE THREAD

**Issue by erkinalp** [EtchedPixels/FUZIX#97]
On m68k platform, FUZIX and Linux can coexist. We will need either of those:
a)Chainloader which loads FUZIX
b)Boot manager to choose among Linux and FUZIX plus (a)
c)GRUB compatible kernel image

**Comment by EtchedPixels** [comment]
ucLinux for Atari ST has been dead since 1999, there is no ucLinux for early Macintosh, ucLinux for Amiga 68000 died a few years later. None of them used grub or grub compatible images.

So basically there is zero overlap.

**Comment by erkinalp** [comment]
x86 family is backwards compatible way from 8086 till AMD64. Later on x86 port, we will tackle on this again. DOS, Linux, BSD and FUZIX may coexist on a 386+. This may remain closed for now.

**Comment by EtchedPixels** [comment]
Also ELKS (Linux 8086), and the loader from that may be ideal
