### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by xmotif** [EtchedPixels/FUZIX#984]
Trying to build FUZIX git for RC2014

(no change to config.h)
FUZIX/Kernel/include/i2c.h:6:26: fatal error: platform_i2c.h: No such file or directory

(add #undef CONFIG_DEV_I2C)
video-macca.c:260: error 20: Undefined identifier 'HW_PROPGFX'
...

**Comment by EtchedPixels** [comment]
Thanks.. let me check what I forgot to commit 8)
